!(import! &self cond-conj-intro)
!(import! &self utils:conj-utils)
!(import! &self utils:util)
!(import! &self utils:rule-ops)
!(import! &self utils:deduction-utils)
!(import! &self deduction)

!(bind! &ruleSpace (new-space))

!(add-reduct &ruleSpace (superpose (
    ;; Rule 1
    (: Rule 1
        (TTV 0)
        (STV 0.5 0.002)  
        (Complexity 1)
        (IMPLICATION
            (AND 
                (Context (STV 0.2 0.1) (AND (
                    (LEFT_SQUARE (STV 0.2 0.1))
                    (STILL_ALIVE (STV 0.2 0.1)))))
                (Action (SEQ_AND (MOVE_RIGHT))))
            (Goal (STV 0.2 0.1) (AND (
                    (CENTER_SQUARE (STV 0.2 0.1))
                    (STILL_ALIVE (STV 0.2 0.1)))
        )) 
    ))

    ;; Rule 3
    (: Rule 3
        (TTV 0)
        (STV 0.5 0.002)  
        (Complexity 1)
        (IMPLICATION 
            (AND 
                (Context (STV 0.2 0.1) (AND (
                    (LEFT_SQUARE (STV 0.2 0.1))
                    (STILL_ALIVE (STV 0.2 0.1)))))
                (Action (SEQ_AND (MOVE_RIGHT))))
            (Goal (STV 0.2 0.1) (AND (
                    (CENTER_SQUARE (STV 0.2 0.1))
                    (DEAD (STV 0.2 0.1)))
        )) 
    ))

    ;; Rule 2
    (: Rule 2
        (TTV 0)
        (STV 0.5 0.002)  
        (Complexity 1)
        (IMPLICATION 
            (AND 
                (Context (STV 0.2 0.1) (AND (
                    (CENTER_SQUARE (STV 0.2 0.1))
                    (STILL_ALIVE (STV 0.2 0.1)))))
                (Action (SEQ_AND (MOVE_RIGHT)) ) )
            (Goal (STV 0.2 0.1) (AND (
                    (RIGHT_SQUARE (STV 0.2 0.1))
                    (STILL_ALIVE (STV 0.2 0.1)))
        )) 
    ))
)))

(= (pln-reasoning $ruleSpace) (
    let* (
        ($deductionResults (pln-deduction $ruleSpace))
        ($conjunctionResults (pln-conjunction $ruleSpace))

        ($_ (println! (Deduction Results: $deductionResults)))
        ($_ (println! (Conjunction Results: $conjunctionResults)))
        ($reasonedRules (union-atom $deductionResults $conjunctionResults))
        ;; Give them unique IDs, TTV, and Complexity
    ) $reasonedRules
))

!(pln-reasoning &ruleSpace)